version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # Specify the Node.js version
    commands:
      - npm install  # Install dependencies
  build:
    commands:
      - npm run build  # Build the React application
artifacts:
  files:
    - '**/*'  # Upload all files generated in the build
  base-directory: build  # The directory where build files are generated
